CRU_Kamar_Hotel/urls.py
from django.urls import path
from CRU_Kamar_Hotel.views import tambah_kamar,daftar_kamar,kamar_tidak_ada,delete_room_view



app_name = 'CRU_Kamar_Hotel'


urlpatterns = [
    path('form-tambah-kamar', tambah_kamar, name = 'show_tambahKamar'),
    path('kamar-Hotel', daftar_kamar, name = 'show_daftarKamar'),
    path('kamar-Hotel-Tidak-Ada', kamar_tidak_ada, name = 'show_kamarTidakAda'),
    path('delete-room', delete_room_view, name = 'delete_room'),
]

authentication/urls.py
from django.urls import path
from .views import login_user, logout_user
app_name = 'authentication'

urlpatterns = [
        path('login/', login_user, name='login_user'),
        path('logout/', logout_user, name='logout_user'),
        # path('registration/', view.registration, name='registration'),

]

kamar_hotel/urls.py
from django.urls import path
from .views import *

app_name = 'kamar_hotel'

urlpatterns = [
    path('', get_daftar_reservasi, name='get-daftar-reservasi'),
    path('update/<str:reservation_id>', update_reservasi, name='update-reservasi'),
    path('get-detail/<str:reservation_id>', get_detail_reservasi, name='get-detail-reservasi'),
    path('reservasi-shuttle/<str:reservation_id>', reservasi_shuttle, name='reservasi-shuttle')
]

r_dashboard/urls.py
from django.urls import path
from .views import show_customer_dashboard, show_hotel_dashboard
app_name = 'r_dashboard'

urlpatterns = [
    path('customer', show_customer_dashboard, name='show_customer_dashboard'),
    path('hotel', show_hotel_dashboard, name='show_hotel_dashboard'),
]

sistel/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import show_main


urlpatterns = [
    path('admin/', admin.site.urls),
    path('feedback/', include('complaint_review.urls')),
    path('kamar-hotel/', include('kamar_hotel.urls')),
    path('dashboard/', include('r_dashboard.urls')),
    path('auth/', include('authentication.urls')),
    path('fasilitas-hotel/', include('fasilitas_hotel.urls')),
    path('CRU-Kamar-Hotel/', include('CRU_Kamar_Hotel.urls')),
    path('registration/', include('registration.urls')),
    path('', show_main, name='show_main'),
    path('daftar_hotel/', include('daftar_detail_hotel.urls')),
]

templates/base_customer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block meta %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% endblock meta %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="#">SISTEL</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'r_dashboard:show_customer_dashboard' %}">Dashboard Pengguna</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'daftar_detail_hotel:show_daftar_hotel' %}">Reservasi Pengguna</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'kamar_hotel:get-daftar-reservasi'%}">Pemesanan Kamar</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'complaint_review:show_complaint' %}">Komplain</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'authentication:logout_user' %}">Logout</a>
              </li>
              
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
  </body>
  {% block content %} {% endblock content %}

</html>

templates/base_hotel.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block meta %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% endblock meta %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="#">SISTEL</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'r_dashboard:show_hotel_dashboard' %}">Dashboard Hotel</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'CRU_Kamar_Hotel:show_daftarKamar' %}">Kamar Hotel</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'fasilitas_hotel:fasilitas_hotel' %} ">Fasilitas Hotel</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/kamar-hotel/">List Reservasi Hotel</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'authentication:logout_user' %}">Logout</a>
              </li>
              
            </ul>
          </div>
        </div>
      </nav>
    </header>

    

    {% block content %} {% endblock content %}

    <!-- JavaScript yang diperlukan untuk Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

  </body>

</html>