kamar_hotel/urls.py
from django.urls import path
from .views import *

app_name = 'kamar_hotel'

urlpatterns = [
    path('', get_daftar_reservasi, name='get-daftar-reservasi'),
    path('update/<str:reservation_id>', update_reservasi, name='update-reservasi'),
    path('get-detail/<str:reservation_id>', get_detail_reservasi, name='get-detail-reservasi'),
    path('reservasi-shuttle/<str:reservation_id>', reservasi_shuttle, name='reservasi-shuttle')
]

sistel/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import show_main


urlpatterns = [
    path('admin/', admin.site.urls),
    path('feedback/', include('complaint_review.urls')),
    path('kamar-hotel/', include('kamar_hotel.urls')),
    path('dashboard/', include('r_dashboard.urls')),
    path('auth/', include('authentication.urls')),
    path('fasilitas-hotel/', include('fasilitas_hotel.urls')),
    path('CRU-Kamar-Hotel/', include('CRU_Kamar_Hotel.urls')),
    path('registration/', include('registration.urls')),
    path('', show_main, name='show_main'),
    path('daftar_hotel/', include('daftar_detail_hotel.urls')),
]

kamar_hotel/views.py
from django.shortcuts import render, redirect
import psycopg2
from datetime import datetime, timedelta, timezone
from django.contrib import messages
 
DB_NAME = 'railway'
DB_USER = 'postgres'
DB_PASS = 'bGfD-1fc22D*4fDEC4-d331f-25c6bbe'
DB_HOST = 'monorail.proxy.rlwy.net'
DB_PORT = '59422'

# Create your views here.

def get_daftar_reservasi(request):
    conn = psycopg2.connect(database=DB_NAME,
                        user=DB_USER,
                        password=DB_PASS,
                        host=DB_HOST,
                        port=DB_PORT)
    cur = conn.cursor()
    email = request.COOKIES.get('email')
    role = request.COOKIES.get('role')

    if role == 'customer' :
        cur.execute(f"""

        set search_path to sistel;
        select r.rid, rnum, rsh.datetime, status
        from reservation r join reservation_room on r.rid = rsv_id
        join reservation_status_history rsh on r.rid = rsh.rid
        join reservation_status on rsid = id
        where cust_email = '{email}';
                    
        """)

        data_reservasi =  cur.fetchall()
        is_hotel = False

    
    else :
        cur.execute(f"""

        set search_path to sistel;
        select r.rid, rnum, rsh.datetime, status
        from reservation r join reservation_room on r.rid = rsv_id
        join reservation_status_history rsh on r.rid = rsh.rid
        join reservation_status on rsid = id
        join room ro on rnum = number
        join hotel h on (ro.hotel_name, ro.hotel_branch)=(h.hotel_name, h.hotel_branch)
        where email = '{email}';
                    
        """)

        data_reservasi =  cur.fetchall()
        is_hotel = True

    conn.commit()
    context = {
        "result": data_reservasi,
        "is_hotel": is_hotel
    }
    return render(request, 'daftar-reservasi-kamar.html', context)


def update_reservasi(request, reservation_id):
    conn = psycopg2.connect(database=DB_NAME,
                        user=DB_USER,
                        password=DB_PASS,
                        host=DB_HOST,
                        port=DB_PORT)
    cur = conn.cursor()
    email = request.COOKIES.get('email')
    role = request.COOKIES.get('role')

    if role != 'hotel':
        return redirect('kamar_hotel:get-daftar-reservasi')
    
    if request.method == "POST":
        try:

            status_id = request.POST.get("status")
            cur.execute(f"""
            set search_path to sistel;
            update reservation_status_history
            set rsid = '{status_id}', datetime='{datetime.now(timezone(timedelta(hours=7)))}'
            where rid = '{reservation_id}';
            """)
            conn.commit()
        except Exception as e:
            messages.error(request,str(e))
        finally:
            return redirect('kamar_hotel:get-detail-reservasi', reservation_id = reservation_id)
        

    cur.execute(f"""
    
    set search_path to sistel;
    select r.rid, rnum, rsid
    from reservation r join reservation_room on r.rid = rsv_id
    join reservation_status_history rsh on r.rid = rsh.rid
    where r.rid = '{reservation_id}';
                
    """)

    data_reservasi = cur.fetchone()

    cur.execute(f"""

    set search_path to sistel;
    select * from reservation_status;

    """)

    daftar_status = cur.fetchall()
    context = {"id": data_reservasi[0],
               "nomor": data_reservasi[1],
               "status_id": data_reservasi[2],
               "daftar_status": daftar_status,
               "reservation_id": reservation_id
    }

    return render(request, 'update-status-reservasi.html', context)

def get_detail_reservasi(request, reservation_id):
    conn = psycopg2.connect(database=DB_NAME,
                        user=DB_USER,
                        password=DB_PASS,
                        host=DB_HOST,
                        port=DB_PORT)
    cur = conn.cursor()
        
    cur.execute(f"""

    set search_path to sistel;
    select r.rid, rnum, hotel_name, hotel_branch, rsh.datetime, status
    from reservation r join reservation_room on r.rid = rsv_id
    join reservation_status_history rsh on r.rid = rsh.rid
    join reservation_status on rsid = id
    join room on rnum = number
    where r.rid = '{reservation_id}';
                
    """)

    data_reservasi =  cur.fetchone()

    cur.execute(f"""

    set search_path to sistel;
    select vehicle_num, driver_phonenum, datetime
    from reservation_shuttleservice
    where rsv_id='{reservation_id}'
    ;
    """)

    data_shuttle = cur.fetchone()
    print(data_shuttle)
    print(reservation_id)

    # commit the changes
    conn.commit()
    context = {
        "id" : data_reservasi[0],
        "nomor" : data_reservasi[1],
        "nama_hotel" : data_reservasi[2],
        "cabang_hotel" : data_reservasi[3],
        "tanggal" : data_reservasi[4],
        "status" : data_reservasi[5]
    }

    if data_shuttle:
        context['nomor_kendaraan']=data_shuttle[0]
        context['nomor_driver']=data_shuttle[1]
        context['tanggal_shuttle']=data_shuttle[2]

    return render(request, 'detail-reservasi.html', context)


def reservasi_shuttle(request, reservation_id):
    conn = psycopg2.connect(database=DB_NAME,
                        user=DB_USER,
                        password=DB_PASS,
                        host=DB_HOST,
                        port=DB_PORT)
    cur = conn.cursor()
    email = request.COOKIES.get('email')
    role = request.COOKIES.get('role')

    # if role != 'customer':
    #     return redirect('get-daftar-reservasi')
    
    if request.method == "POST":
        try :

            key = eval(request.POST.get("shuttle_service"))
            print(key)
            cur.execute(f"""
            set search_path to sistel;
            insert into reservation_shuttleservice
            values ('{reservation_id}', '{key[0]}', '{key[1]}', '{datetime.now(timezone(timedelta(hours=7)))}', true);
            """)
            conn.commit()

        except Exception as e:
            messages.error(request, str(e))
        finally:
            return redirect('kamar_hotel:get-detail-reservasi', reservation_id = reservation_id)
            

    cur.execute(f"""

    set search_path to sistel;
    select driver_name, vehicle_brand, vehicle_type, phonenum, platnum
    from shuttle_service join driver on driver_phonenum=phonenum
    join vehicle on vehicle_platnum=platnum;

    """)

    daftar_shuttle_service = cur.fetchall()
    context = {"daftar_shuttle_service": daftar_shuttle_service,
               "reservation_id": reservation_id

    }

    return render(request, 'reservasi-shuttle.html', context)

kamar_hotel/templates/daftar-reservasi-kamar.html
{% extends 'base_customer.html' %}

{% block meta %}
    <title>DAFTAR RESERVASI</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f4f4f4;
        }
        h1 {
            text-align: center;
            color: #333;
        }
        .dashboard-section {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
            padding: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
{% endblock meta %}
{% block content %}


    <h1>DAFTAR RESERVASI KAMAR</h1>

    <div class="dashboard-section">
        <table>
            <tr>
                <th>ID Reservasi</th>
                <th>Nomor Kamar</th>
                <th>Date</th>
                <th>Status Reservasi</th>
                <th>Action</th>
            </tr>
            {%for id, nomor, tanggal, status in result%}
            <tr>
                <td>{{id}}</td>
                <td>{{nomor}}</td>
                <td>{{tanggal|date:"d-m-Y"}}</td>
                <td>{{status}}</td>
                <td>
                    {%if is_hotel%}
                    <button type="button"><a href="{% url 'kamar_hotel:update-reservasi' id%}">Update Reservasi</a></button>
                    {%endif%}
                    <button type="button"><a href="{% url 'kamar_hotel:get-detail-reservasi' id %}">Get Detail</a></button>
                </td>
            </tr>
            {%endfor%}
            
        </table>
    </div>

    
{% endblock content %}

kamar_hotel/templates/detail-reservasi.html
{% extends 'base_customer.html' %}

{% block meta %}
    <title>DETAIL RESERVASI</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f4f4f4;
        }
        h1 {
            text-align: center;
            color: #333;
        }
        .dashboard-section {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
            padding: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
{% endblock meta %}
{% block content %}
    <h1>DETAIL RESERVASI</h1>

    <div class="dashboard-section">
        <h2>KAMAR</h2>
        <table>
            <tr>
                <th>ID Reservasi</th>
                <td>{{id}}</td>
            </tr>
            <tr>
                <th>Nomor Kamar</th>
                <td>{{nomor}}</td>
            </tr>
            <tr>
                <th>Nama Hotel</th> 
                <td>{{nama_hotel}}</td>           
            </tr>    
            <tr>
                <th>Cabang Hotel</th>
                <td>{{cabang_hotel}}</td>
            </tr> 
            <tr>
                <th>Tanggal</th>
                <td>{{tanggal|date:"d-m-Y"}}</td>
            </tr>  
            <tr>
                <th>Status</th>
                <td>{{status}}</td>
            </tr>       
        </table>       
    </div>

    <div class="dashboard-section">
        <h2>SHUTTLE</h2>
        <table>
            {%if not nomor_kendaraan%}
            <tr>
                <td>Tidak ada reservasi untuk shuttle pada reservasi ini.</td>
            </tr>
            <tr>
                <td><button type="button">
                <a href="{% url 'kamar_hotel:reservasi-shuttle' id %}">Reservasi Shuttle</a>
                </button></td>
            </tr>  
            {%else%}
            <tr>
                <th>ID Reservasi:</th>
                <td>{{id}}</td>
            </tr>
            <tr>
                <th>Nomor Kendaraan:</th>
                <td>{{nomor_kendaraan}}</td>
            </tr>
            <tr>
                <th>Nomor HP Driver:</th>
                <td>{{nomor_driver}}</td>
            </tr>
            <tr>
                <th>Tanggal:</th>
                <td>{{tanggal_shuttle|date:"d-m-Y"}}</td>
            </tr>
            {%endif%}   
        </table>       
    </div>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message|truncatewords:4 }}
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    <button type="button"> 
        <a href="{%url 'kamar_hotel:get-daftar-reservasi'%}">Back</a>
    </button>

    
{% endblock content %}

kamar_hotel/templates/reservasi-shuttle.html
{% extends 'base_customer.html' %}

{% block meta %}
    <title>UPDATE STATUS RESERVASI</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f4f4f4;
        }
        h1 {
            text-align: center;
            color: #333;
        }
        .dashboard-section {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
            padding: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
{% endblock meta %}
{% block content %}

    <h1>RESERVASI SHUTTLE</h1>

    <div class="dashboard-section">
        <form action="{%url 'kamar_hotel:reservasi-shuttle' reservation_id%}" method="post">
            {%csrf_token%}
            <table>
                <tr>
                    <th>ID Reservasi</th>
                    <td><input type="text" name="id" value="{{reservation_id}}" readonly></td>
                </tr>
                <tr>
                    <th>Kendaraan</th>
                    <td><select name="shuttle_service">
                        {%for driver_name, vehicle_name, vehicle_type, phonenum, platnum in daftar_shuttle_service%}
                            <option value="('{{platnum}}', '{{phonenum}}')">
                            {{driver_name}}, {{vehicle_name}}, {{vehicle_type}}, {{platnum}}
                            </option>
                        {%endfor%}
                        </select></td>
                </tr>              
            </table>
            <input type="submit" value="Submit">
        </form>
        
    </div>
{% endblock content %}

kamar_hotel/templates/update-status-reservasi.html
{% extends 'base_customer.html' %}

{% block meta %}
    <title>UPDATE STATUS RESERVASI</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f4f4f4;
        }
        h1 {
            text-align: center;
            color: #333;
        }
        .dashboard-section {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
            padding: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
{% endblock meta %}
{% block content %}
    <h1>UPDATE STATUS RESERVASI</h1>

    <div class="dashboard-section">
        <form action="{%url 'kamar_hotel:update-reservasi' reservation_id%}" method="post">
            {%csrf_token%}
            <table>
                <tr>
                    <th>ID Reservasi</th>
                    <td><input type="text" name="id" value="{{id}}" readonly></td>
                </tr>
                <tr>
                    <th>Nomor Kamar</th>
                    <td><input type="text" name="nomor" value="{{nomor}}" readonly></td>
                </tr>
                <tr>
                    <th>Status</th>
                    <td><select name="status">
                    {%for id, nama in daftar_status%}
                        <option value="{{id}}" {%if id == status_id%} selected {%endif%}>
                        {{nama}}
                        </option>
                    {%endfor%}
                    </select></td>
                </tr>              
            </table>
            <input type="submit" value="update">
        </form>
        
    </div>

{% endblock content %}