complaint_review/urls.py
from django.urls import path
from complaint_review.views import show_complaint_form, show_review_form

app_name = 'complaint_review'

urlpatterns = [
    path('complaint/', show_complaint_form, name = 'show_complaint'),
    path('review/<str:hotel_name>/', show_review_form, name = 'show_review'),
]

daftar_detail_hotel/urls.py
from django.urls import path
from .views import *

app_name = 'daftar_detail_hotel'

urlpatterns = [
    path('', show_daftar_hotel, name='show_daftar_hotel'),
    path('detail-hotel/<str:hotel_name>/', show_detail_hotel, name = 'show_detail_hotel')
]

sistel/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import show_main


urlpatterns = [
    path('admin/', admin.site.urls),
    path('feedback/', include('complaint_review.urls')),
    path('kamar-hotel/', include('kamar_hotel.urls')),
    path('dashboard/', include('r_dashboard.urls')),
    path('auth/', include('authentication.urls')),
    path('fasilitas-hotel/', include('fasilitas_hotel.urls')),
    path('CRU-Kamar-Hotel/', include('CRU_Kamar_Hotel.urls')),
    path('registration/', include('registration.urls')),
    path('', show_main, name='show_main'),
    path('daftar_hotel/', include('daftar_detail_hotel.urls')),
]

daftar_detail_hotel/models.py
from django.db import models

# Create your models here.

daftar_detail_hotel/forms.py
from django import forms

class SearchForm(forms.Form):
    minPrice = forms.IntegerField(widget=forms.NumberInput(attrs={'id': 'minPrice_field'}))
    maxPrice = forms.IntegerField(widget=forms.NumberInput(attrs={'id': 'maxPrice_field'}))

daftar_detail_hotel/views.py
from django.shortcuts import render
from .forms import SearchForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from .queries import *

# Create your views here.

def show_daftar_hotel(request):
    try:
        email_user = request.COOKIES['email']
        fname_user = request.COOKIES['fname']
        lname_user = request.COOKIES['lname']
    except:
        return HttpResponseRedirect(reverse("authentication:login_user"))
    
    if request.method == "GET":
        form = SearchForm(request.GET)
        if form.is_valid():
            minPrice = form.cleaned_data['minPrice']
            maxPrice = form.cleaned_data['maxPrice']
            hotels = get_hotels(minPrice, maxPrice)
            context = {
                "form" : form,
                "hotel_list" : hotels
            }
            return render(request, "daftar_hotel.html", context)
    else:
        form = SearchForm()
    context = {
        "email" : email_user,
        "fname" : fname_user,
        "lname" : lname_user,
        "form"  : form,
    }
    return render(request, 'daftar_hotel.html', context)

def show_detail_hotel(request, hotel_name):
    try:
        email_user = request.COOKIES['email']
        fname_user = request.COOKIES['fname']
        lname_user = request.COOKIES['lname']
    except:
        return HttpResponseRedirect(reverse("authentication:login_user"))
    
    hotel_detail = get_hotel_detail(hotel_name)
    room_list = get_room_list(hotel_name)
    context = {
        "hotel_detail" : hotel_detail,
        "room_list" : room_list
    }

    return render(request, 'detail_hotel.html', context)

daftar_detail_hotel/templates/daftar_hotel.html
{% extends 'base_customer.html' %}

{% block content %}

    <div class=" container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="text-center mb-5">Reservasi Kamar Hotel</h2>

                <form method="GET">
                    {% csrf_token %} 

                    <!-- <div class="mb-3">
                        <label for="minPrice_field" class="form-label">Minimum Price:</label>
                        <input class="form-control" id="minPrice_field">
                    </div>

                    <div class="mb-3">
                        <label for="maxPrice_field" class="form-label">Maximum Price:</label>
                        <input class="form-control" id="maxPrice_field">
                    </div> -->

                    <table>{{form.as_table}}</table>
                    
                    <input class="btn btn-primary mb-3" type="submit" name="submit" value="Submit">
                </form>

                <div>
                    {% if hotel_list %}
                        {% for row in hotel_list %}
                            <div class="card mb-3">
                                <div class="card-body">
                                    <h5 class="card-title"> {{ row.0 }} </h5>
                                    <p class="card-text"> Rating: {{ row.1 }} </p>
                                    <a href="{% url 'daftar_detail_hotel:show_detail_hotel' row.0 %}" class="stretched-link"></a>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <p>No hotel found.</p>
                    {% endif %}
                </div>
                
            </div>
        </div>
    </div>

{% endblock content %}

daftar_detail_hotel/templates/detail_hotel.html
{% extends 'base_customer.html' %}

{% block content %}

    <div class=" container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                {% for row in hotel_detail%}
                <h2 class="text-center mb-5">{{ row.0 }}</h2>
                <table class="table mb-4">
                    <tr>
                        <th>Deskripsi</th>
                        <td>{{ row.1 }}</td>
                    </tr>
                    <tr>
                        <th>NIB</th>
                        <td>{{ row.2 }}</td>
                    </tr>
                    <tr>
                        <th>Rating</th>
                        <td>{{ row.3 }}</td>
                    </tr>
                    <tr>
                        <th>Alamat</th>
                        <td>{{ row.4 }}, {{ row.5 }}, {{ row.6 }}, {{ row.7 }}</td>
                    </tr>
                    <tr>
                        <th>Min Check-In</th>
                        <td>{{ row.8 }}</td>
                    </tr>
                    
                    <tr>
                        <th>Min Check-Out</th>
                        <td>{{ row.9 }}</td>
                    </tr>
                </table>

                <h3 class="mt-5">Kamar Tersedia</h3>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Nomor Kamar</th>
                            <th>Harga per Malam</th>
                            <th>Actions</th>
                        </tr>
                    </thead>

                    <tbody class="table-group-divider">
                        {% for row in room_list %}
                        <tr>
                            <td>{{ row.0 }}</td>
                            <td>{{ row.1 }}</td>
                            <td><button type="button" class="btn btn-primary mb-3" onclick="bookReservasi()">Reservasi</button></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <a href="{% url 'complaint_review:show_review' row.0 %}" class="btn btn-primary mb-3">Add Review</a>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}