fasilitas_hotel/urls.py
from django.urls import path
from .views import *

app_name = "fasilitas_hotel"

urlpatterns = [
    path('', fasilitas_hotel, name='fasilitas_hotel'),
    # path('show-fasilitas/', show_fasilitas, name = 'show_fasilitas'),
    path('add-fasilitas/', add_fasilitas_hotel, name='add_fasilitas_hotel'), 
    path('update-fasilitas/', update_fasilitas_hotel, name = 'update_fasilitas_hotel'),
    path('delete-fasilitas/<str:nama_fasilitas>', delete_fasilitas_hotel, name = 'delete_fasilitas_hotel'),
]

sistel/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import show_main


urlpatterns = [
    path('admin/', admin.site.urls),
    path('feedback/', include('complaint_review.urls')),
    path('kamar-hotel/', include('kamar_hotel.urls')),
    path('dashboard/', include('r_dashboard.urls')),
    path('auth/', include('authentication.urls')),
    path('fasilitas-hotel/', include('fasilitas_hotel.urls')),
    path('CRU-Kamar-Hotel/', include('CRU_Kamar_Hotel.urls')),
    path('registration/', include('registration.urls')),
    path('', show_main, name='show_main'),
    path('daftar_hotel/', include('daftar_detail_hotel.urls')),
]

fasilitas_hotel/models.py
from django.db import models

# Create your models here.

fasilitas_hotel/forms.py
from django import forms

class AddFasilitasForm(forms.Form):
    nama_fasilitas = forms.CharField(widget = forms.Textarea)

fasilitas_hotel/views.py
from django.shortcuts import render
from .forms import AddFasilitasForm
from django.http import HttpResponseRedirect
from .queries import submit_fasilitas, get_fasilitas, get_hotel_by_email, update_fasilitas, delete_fasilitas
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.http import urlencode

# Create your views here.

def fasilitas_hotel(request):
    email = request.COOKIES.get('email')
    hotel = get_hotel_by_email(email)
    facilities = get_fasilitas(nama_hotel=hotel.get('hotel_name'), hotel_branch=hotel.get('hotel_branch'))

    context = {
        'data': hotel,
        'facilities': facilities
    }

    return render(request, 'fasilitas_hotel.html', context)


@csrf_exempt
def add_fasilitas_hotel(request):
    if request.method == 'POST':
        email = request.COOKIES.get('email')
        hotel = get_hotel_by_email(email)
        nama_fasilitas = request.POST['nama_fasilitas']
        submit_fasilitas(hotel.get('hotel_name'), hotel.get('hotel_branch'), nama_fasilitas)
        return redirect('fasilitas_hotel:fasilitas_hotel')
    else:
        return render(request, 'add_fasilitas.html')


@csrf_exempt
def update_fasilitas_hotel(request):
    if request.method == 'POST':
        email = request.COOKIES.get('email')
        hotel = get_hotel_by_email(email)
        new_fasilitas = request.POST['new_fasilitas']
        old_fasilitas = request.POST['old_fasilitas']
        update_fasilitas(hotel.get('hotel_name'), hotel.get('hotel_branch'), old_fasilitas, new_fasilitas)
        return redirect('fasilitas_hotel:fasilitas_hotel')
    else:
        fasilitas = request.GET.get('fasilitas')
        return render(request, 'edit_fasilitas.html', {'fasilitas': fasilitas})
    

@csrf_exempt
def delete_fasilitas_hotel(request, nama_fasilitas):
    email = request.COOKIES.get('email')
    hotel = get_hotel_by_email(email)
    delete_fasilitas(hotel.get('hotel_name'), hotel.get('hotel_branch'), nama_fasilitas)
    return redirect('fasilitas_hotel:fasilitas_hotel')


# def show_fasilitas(request):
#     email = request.COOKIES.get('email')
#     hotel = get_hotel_by_email(email)
#     facilities = get_fasilitas(hotel.get('hotel_name'), hotel.get('hotel_branch'))
#     context = {
#         'facilities': facilities
#     }
    
#     return HttpResponse(context)

fasilitas_hotel/templates/add_fasilitas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <title>Add Facility</title>

</head>
<body>
    <div class=" container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="text-center mb-5">Tambah Fasilitas</h2>

                <form class="add-facility-form">

                    <div class="mb-3">
                        <label for="facilityName" class="form-label">Nama:</label>
                        <input class="form-control" id="facilityName" placeholder="~~~" required>
                    </div>

                    <button type="button" class="btn btn-primary mx-auto" onclick="addFacility()">Tambah</button>

                </form>
            </div>
        </div>
    </div>

    <script>
        function addFacility() {
            //TODO: func here
            return false;
        }
    </script>

</body>
</html>

fasilitas_hotel/templates/edit_fasilitas.html
{% extends 'base_hotel.html' %}

{% block meta %}

{% endblock meta %}
{% block content %}

<body>
    <div class=" container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="text-center mb-5">Edit Fasilitas</h2>

                <form action="{% url 'fasilitas_hotel:update_fasilitas_hotel' %}" method="post" class="add-facility-form">
                    {% csrf_token %}
                    <input type="hidden" value="{{ fasilitas }}" class="form-control" name="old_fasilitas" id="facilityName" placeholder="Nama Fasilitas" required>
                    <div class="mb-3">
                        <label for="facilityName" class="form-label">Nama Fasilitas:</label>
                        <input class="form-control" name="new_fasilitas" id="facilityName" placeholder="{{ fasilitas }}" required>
                    </div>

                    <button type="submit" class="btn btn-primary mx-auto">Simpan</button>

                </form>
            </div>
        </div>
    </div>

    <script>
        function addFacility() {
            //TODO: func here
            return false;
        }
    </script>

</body>
</html>

{% endblock content %}

fasilitas_hotel/templates/fasilitas_hotel.html
{% extends 'base_hotel.html' %}

{% block meta %}

{% endblock meta %}
{% block content %}

<body>
    <div class=" container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="text-center mb-5">Fasilitas Hotel</h2>

                <div class="facility-section">
                    <a href="{% url 'fasilitas_hotel:add_fasilitas_hotel' %}">
                        <button type="button" class="btn btn-primary" onclick="addFacility()">Tambah Fasilitas</button>
                    </a>

                    <br><br>

                    <table class="table table-hover table-strpied-columns" id="facilityTable">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Nama Fasilitas</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            {% if facilities|length > 0 %}
                                {% for facility in facilities %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ facility.facility }}</td>
                                    <td class="d-flex gap-1">
                                        <form action="{% url 'fasilitas_hotel:update_fasilitas_hotel' %}" method="get">
                                            <input type="hidden" name="fasilitas" value="{{ facility.facility }}">
                                            <button type="submit" class="btn btn-primary mb-3">Update</button>
                                        </form>
                                        <a href="{% url 'fasilitas_hotel:delete_fasilitas_hotel' facility.facility %}">
                                            <button type="button" class="btn btn-danger mb-3">Delete</button>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="3" class="text-center">
                                        Belum ada fasilitas.
                                    </td>
                                </tr>
                            {% endif %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>

    <script>
        function addFacility() {
            //TODO: func here
            return -1;
        }

        function updateFacility() {
            //TODO: func here
            return -1;
        }

        function deleteFacility() {
            //TODO: func here
            return -1;
        }
    </script>

</body>
</html>

{% endblock content %}

fasilitas_hotel/templates/update_fasilitas.html
{% extends 'base_hotel.html' %}

{% block meta %}

{% endblock meta %}
{% block content %}

<body>
    <div class=" container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="text-center mb-5">Ubah Fasilitas</h2>

                <form class="update-facility-form">

                    <div class="mb-3">
                        <label for="facilityName" class="form-label">Nama baru:</label>
                        <input class="form-control" id="facilityName" placeholder="~~~" required>
                    </div>

                    <button type="button" class="btn btn-primary mx-auto" onclick="updateFacility()">Ubah</button>

                </form>
            </div>
        </div>
    </div>

    <script>
        function updateFacility() {
            //TODO: func here
            return false;
        }
    </script>
</body>
</html>

{% endblock content %}